name: Release

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push format-json
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:format-json"
          push: true
          platforms: linux/amd64,linux/arm64
          tags: sparkymat/fd-format-json:latest
      - name: Build and push s3-ls
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:s3-ls"
          push: true
          platforms: linux/amd64,linux/arm64
          tags: sparkymat/fd-s3-ls:latest
